version: '3.7'

services:
  main:
    container_name: chest-checker
    build: .
    ports:
      - 3000:3000
    command: npm run start
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'